"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Task = { status: string; priority: string; brand_id: string | null; channel_id: string | null; department_id: string | null; assigned_to: string | null };
type Item = { id: string; name: string };
function countsBy<T extends string | null>(tasks: Task[], key: keyof Task, names: Record<string, string>) { const counts: Record<string, number> = {}; for (const task of tasks) { const value = task[key] as T; const label = value ? names[value] ?? "Unclassified" : "Unclassified"; counts[label] = (counts[label] ?? 0) + 1; } return Object.entries(counts).sort((a, b) => b[1] - a[1]); }

export default function ReportsPage() {
  const [loading, setLoading] = useState(true); const [allowed, setAllowed] = useState(false); const [tasks, setTasks] = useState<Task[]>([]); const [maps, setMaps] = useState<Record<string, Record<string, string>>>({});
  useEffect(() => { async function load() { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("company_id, role, can_view_reports").eq("id", auth.user.id).single(); const canManage = ["admin", "owner"].includes(profile?.role ?? "") || profile?.can_view_reports === true; setAllowed(canManage); if (!profile || !canManage) { setLoading(false); return; } const [tasksResult, brandResult, channelResult, departmentResult, personResult] = await Promise.all([supabase.from("tasks").select("status, priority, brand_id, channel_id, department_id, assigned_to").eq("company_id", profile.company_id), supabase.from("brands").select("id, name"), supabase.from("channels").select("id, name").eq("company_id", profile.company_id), supabase.from("departments").select("id, name").eq("company_id", profile.company_id), supabase.from("profiles").select("id, full_name, email").eq("company_id", profile.company_id)]); const toMap = (items: Item[]) => Object.fromEntries(items.map((item) => [item.id, item.name])); setMaps({ brand_id: toMap(brandResult.data ?? []), channel_id: toMap(channelResult.data ?? []), department_id: toMap(departmentResult.data ?? []), assigned_to: Object.fromEntries((personResult.data ?? []).map((person) => [person.id, person.full_name || person.email || "Team member"])) }); setTasks(tasksResult.data ?? []); setLoading(false); } load(); }, []);
  const overdueRisk = useMemo(() => tasks.filter((task) => ["blocked", "waiting", "rework", "rejected"].includes(task.status)).length, [tasks]);
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-slate-950 text-white">Loading reports...</main>;
  if (!allowed) return <main className="flex min-h-screen items-center justify-center bg-slate-950 text-white">Report access required.</main>;
  const sections: Array<[string, keyof Task]> = [["Department workload", "department_id"], ["Brand workload", "brand_id"], ["Channel workload", "channel_id"], ["Assignment workload", "assigned_to"]];
  return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><section className="mx-auto max-w-6xl"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-sm font-semibold text-cyan-300">FlowDesk</p><h1 className="mt-1 text-3xl font-bold">Workload Reports</h1><p className="mt-2 text-slate-400">Current task distribution across your company.</p></div><Link href="/dashboard" className="rounded-xl border border-white/20 px-5 py-2 text-sm font-semibold">Dashboard</Link></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Total Tasks" value={tasks.length}/><Metric label="Blocked / Rework" value={overdueRisk}/><Metric label="Under Review" value={tasks.filter((task) => ["under_review", "submitted"].includes(task.status)).length}/></div><div className="mt-8 grid gap-6 lg:grid-cols-2">{sections.map(([title, key]) => <section key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="font-semibold">{title}</h2><div className="mt-4 space-y-3">{countsBy(tasks, key, maps[key] ?? {}).map(([name, count]) => <div key={name} className="flex justify-between rounded-xl bg-slate-900 px-4 py-3"><span>{name}</span><span className="font-semibold text-cyan-300">{count}</span></div>)}{tasks.length === 0 && <p className="text-sm text-slate-400">No tasks yet.</p>}</div></section>)}</div></section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>; }
