"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Row={id:string;user_id:string;login_at:string;last_seen_at:string;logout_at:string|null;attendance_status:string;work_mode:string;expected_end_at:string|null};
export default function AttendancePage(){const [rows,setRows]=useState<Row[]>([]);const [people,setPeople]=useState<Record<string,string>>({});const [allowed,setAllowed]=useState(false);const [status,setStatus]=useState("all");const [day,setDay]=useState("");const [error,setError]=useState("");
 useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from("profiles").select("company_id,role,can_manage_people").eq("id",user.id).single();const manager=["admin","owner"].includes(p?.role??"")||p?.can_manage_people===true;setAllowed(manager);let q=supabase.from("attendance_sessions").select("id,user_id,login_at,last_seen_at,logout_at,attendance_status,work_mode,expected_end_at").eq("company_id",p?.company_id).order("login_at",{ascending:false}).limit(500);if(!manager)q=q.eq("user_id",user.id);if(status!=="all")q=q.eq("attendance_status",status);if(day)q=q.gte("login_at",`${day}T00:00:00`).lt("login_at",`${day}T23:59:59`);const [a,ps]=await Promise.all([q,supabase.from("profiles").select("id,full_name,email").eq("company_id",p?.company_id)]);if(a.error)setError(a.error.message);setRows(a.data??[]);setPeople(Object.fromEntries((ps.data??[]).map(x=>[x.id,x.full_name||x.email])))}load()},[day,status]);
 const summary=useMemo(()=>Object.fromEntries(["present","late","overtime","on_leave"].map(s=>[s,rows.filter(r=>r.attendance_status===s).length])),[rows]);
 function csv(){const body=["Person,Status,Login,Last seen,Logout,Work mode",...rows.map(r=>`"${people[r.user_id]??""}",${r.attendance_status},${r.login_at},${r.last_seen_at},${r.logout_at??""},${r.work_mode}`)].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/csv"}));a.download="flowdesk-attendance.csv";a.click();}
 return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><section className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="text-sm font-semibold text-cyan-300">FlowDesk</p><h1 className="mt-1 text-3xl font-bold">Attendance</h1><p className="mt-2 text-slate-400">Simple attendance visibility, exceptions, and policy outcomes.</p></div><div className="flex gap-3"><button onClick={csv} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Export CSV</button><Link href="/dashboard" className="rounded-xl border border-white/20 px-4 py-2 text-sm">Dashboard</Link></div></header>{error&&<p className="mt-4 text-red-300">{error}</p>}<div className="mt-6 grid gap-3 sm:grid-cols-4">{Object.entries(summary).map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase text-slate-400">{k.replace("_"," ")}</p><p className="mt-1 text-2xl font-bold">{v}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-3"><input type="date" value={day} onChange={e=>setDay(e.target.value)} className="rounded-xl bg-slate-900 px-3 py-2 text-white"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl bg-slate-900 px-3 py-2"><option value="all">All statuses</option><option value="present">Present</option><option value="late">Late</option><option value="overtime">Overtime</option><option value="on_leave">On leave</option></select></div><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-white/5 text-slate-400"><tr><th className="p-4">Person</th><th className="p-4">Status</th><th className="p-4">Login</th><th className="p-4">Last seen</th><th className="p-4">Logout</th><th className="p-4">Mode</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/10"><td className="p-4">{people[r.user_id]??"Team member"}</td><td className="p-4 capitalize text-cyan-200">{r.attendance_status.replace("_"," ")}</td><td className="p-4 text-slate-300">{new Date(r.login_at).toLocaleString("en-IN")}</td><td className="p-4 text-slate-300">{new Date(r.last_seen_at).toLocaleString("en-IN")}</td><td className="p-4 text-slate-300">{r.logout_at?new Date(r.logout_at).toLocaleString("en-IN"):"Currently working"}</td><td className="p-4 capitalize">{r.work_mode}</td></tr>)}</tbody></table></div>{!allowed&&<p className="mt-4 text-sm text-slate-500">You can see your own attendance. Admins and authorized managers can see company attendance.</p>}</section></main>}
