"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Task = { id: string; title: string; priority: string; status: string; due_date: string | null; assigned_to: string | null };
type Person = { id: string; full_name: string | null; email: string | null };

export default function ReviewsPage() {
  const [loading, setLoading] = useState(true); const [allowed, setAllowed] = useState(false);
  const [tasks, setTasks] = useState<Task[]>([]); const [people, setPeople] = useState<Record<string, Person>>({});
  useEffect(() => { async function load() { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setLoading(false); return; } const { data: profile } = await supabase.from("profiles").select("company_id, role, can_review_tasks").eq("id", auth.user.id).single(); const canReview = ["admin", "owner", "manager"].includes(profile?.role ?? "") || profile?.can_review_tasks; setAllowed(Boolean(canReview)); if (!profile || !canReview) { setLoading(false); return; } const [taskResult, personResult] = await Promise.all([supabase.from("tasks").select("id, title, priority, status, due_date, assigned_to").eq("company_id", profile.company_id).in("status", ["under_review", "submitted"]).order("submitted_at", { ascending: true }), supabase.from("profiles").select("id, full_name, email").eq("company_id", profile.company_id)]); const map: Record<string, Person> = {}; for (const person of personResult.data ?? []) map[person.id] = person; setPeople(map); setTasks(taskResult.data ?? []); setLoading(false); } load(); }, []);
  if (loading) return <main className="flex min-h-screen items-center justify-center bg-slate-950 text-white">Loading review queue...</main>;
  if (!allowed) return <main className="flex min-h-screen items-center justify-center bg-slate-950 px-6 text-white"><section className="rounded-3xl border border-white/10 bg-white/10 p-8 text-center"><h1 className="text-2xl font-bold">Review permission required</h1><Link href="/dashboard" className="mt-5 inline-block text-cyan-300">Back to Dashboard</Link></section></main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><section className="mx-auto max-w-5xl"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-sm font-semibold text-cyan-300">FlowDesk</p><h1 className="mt-1 text-3xl font-bold">Review Queue</h1><p className="mt-2 text-slate-400">Tasks waiting for a review decision.</p></div><Link href="/dashboard" className="rounded-xl border border-white/20 px-5 py-2 text-sm font-semibold">Dashboard</Link></header>{tasks.length === 0 ? <div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-8 text-slate-400">Nothing is waiting for review.</div> : <div className="mt-8 space-y-3">{tasks.map((task) => <Link key={task.id} href={`/tasks/${task.id}`} className="block rounded-2xl border border-white/10 bg-slate-900 p-5 hover:border-cyan-400/40"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{task.title}</h2><p className="mt-1 text-sm text-slate-400">{task.assigned_to ? people[task.assigned_to]?.full_name || people[task.assigned_to]?.email || "Assigned" : "Unassigned"} · Due {task.due_date ?? "not set"}</p></div><span className="rounded-full bg-blue-400/10 px-3 py-1 text-xs font-semibold text-blue-300">{task.status.replaceAll("_", " ")}</span></div></Link>)}</div>}</section></main>;
}
