"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Person = { id: string; full_name: string | null; email: string | null; role: string | null; can_create_tasks: boolean; can_review_tasks: boolean; is_active: boolean };
export default function PeopleSettingsPage() {
  const [loading,setLoading]=useState(true); const [allowed,setAllowed]=useState(false); const [people,setPeople]=useState<Person[]>([]); const [error,setError]=useState(""); const [saving,setSaving]=useState<string | null>(null);
  async function load(){const {data:auth}=await supabase.auth.getUser();if(!auth.user){setLoading(false);return;}const {data:profile}=await supabase.from("profiles").select("company_id,role").eq("id",auth.user.id).single();const canManage=["admin","owner","manager"].includes(profile?.role??"");setAllowed(canManage);if(profile&&canManage){const {data}=await supabase.from("profiles").select("id,full_name,email,role,can_create_tasks,can_review_tasks,is_active").eq("company_id",profile.company_id).order("full_name");setPeople(data??[]);}setLoading(false);}
  useEffect(()=>{ // eslint-disable-next-line react-hooks/set-state-in-effect
    load();},[]);
  async function update(person:Person, field:"can_create_tasks"|"can_review_tasks"){setSaving(person.id);setError("");const {error:rpcError}=await supabase.rpc("update_profile_permissions",{target_user_id:person.id,allow_task_creation:field==="can_create_tasks"?!person.can_create_tasks:person.can_create_tasks,allow_review:field==="can_review_tasks"?!person.can_review_tasks:person.can_review_tasks});setSaving(null);if(rpcError)setError(rpcError.message);else await load();}
  if(loading)return <main className="flex min-h-screen items-center justify-center bg-slate-950 text-white">Loading people…</main>;
  if(!allowed)return <main className="flex min-h-screen items-center justify-center bg-slate-950 text-white">Manager access required.</main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-8 text-white"><section className="mx-auto max-w-5xl"><header className="flex justify-between border-b border-white/10 pb-6"><div><p className="text-sm font-semibold text-cyan-300">FlowDesk</p><h1 className="mt-1 text-3xl font-bold">People & Permissions</h1><p className="mt-2 text-slate-400">Set who may create tasks or review work.</p></div><Link href="/dashboard" className="rounded-xl border border-white/20 px-5 py-2 text-sm font-semibold">Dashboard</Link></header>{error&&<p className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-8 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-white/5 text-slate-400"><tr><th className="px-4 py-3">Person</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Create Tasks</th><th className="px-4 py-3">Review Work</th></tr></thead><tbody>{people.map(person=><tr key={person.id} className="border-t border-white/10"><td className="px-4 py-3"><p className="font-medium">{person.full_name||person.email}</p><p className="text-xs text-slate-500">{person.email}</p></td><td className="px-4 py-3 capitalize">{person.role}</td><td className="px-4 py-3"><button disabled={saving===person.id} onClick={()=>update(person,"can_create_tasks")} className={`rounded-lg px-3 py-2 ${person.can_create_tasks?"bg-cyan-400 text-slate-950":"border border-white/20"}`}>{person.can_create_tasks?"Allowed":"Disabled"}</button></td><td className="px-4 py-3"><button disabled={saving===person.id} onClick={()=>update(person,"can_review_tasks")} className={`rounded-lg px-3 py-2 ${person.can_review_tasks?"bg-cyan-400 text-slate-950":"border border-white/20"}`}>{person.can_review_tasks?"Allowed":"Disabled"}</button></td></tr>)}</tbody></table></div></section></main>;
}
